import type { QuickCheckInput, QuickFieldKey, QuickFieldMeta, UnknownSelection } from '@/lib/types';

export const quickCheckDefaults: QuickCheckInput = {
  useDayRate: false,
  hourlyRate: 55,
  dayRate: 440,
  jobsPerMonth: 16,
  travelHoursPerWorkday: 1,
  parkingPerJob: 10,
  adminHoursPerWeek: 5,
  urgentTripsPerMonth: 2,
  callbackHoursPerMonth: 2,
  forgotMaterialPerMonth: 75,
  underpricedPercent: 5,
};

export const advancedDefaults = {
  workdaysPerYear: 230,
  billableHoursPerDay: 6,
  paymentTermDays: 0,
  outstandingAmount: 0,
  toolsDepreciationPerMonth: 0,
  fixedCostsPerMonth: 0,
  revisitJobsPerMonth: 0,
  revisitHoursPerVisit: 1,
  avgHoursPerJob: 6,
  travelNotBilledFactor: 0.5,
};

export const modelAssumptionDefaults = {
  workdaysPerMonth: 20,
  urgentTripHoursDefault: 0.75,
  avgHoursPerJobDefault: 6,
  travelNotBilledFactor: 0.5,
  cashflowAnnualRate: 0.06,
  yearMultiplier: 12,
} as const;

export const quickFieldOrder: QuickFieldKey[] = [
  'hourlyRate',
  'dayRate',
  'jobsPerMonth',
  'travelHoursPerWorkday',
  'parkingPerJob',
  'adminHoursPerWeek',
  'urgentTripsPerMonth',
  'callbackHoursPerMonth',
  'forgotMaterialPerMonth',
  'underpricedPercent',
];

export const quickFieldMeta: Record<QuickFieldKey, QuickFieldMeta> = {
  hourlyRate: {
    key: 'hourlyRate',
    label: 'Uurtarief (excl. btw)',
    tooltip: 'Je standaard declarabele uurprijs zonder btw.',
    typicalRange: 'Meestal 45–65 €/uur (bij timmermannen/ZZP)',
    min: 25,
    max: 120,
    step: 1,
    unit: '€/uur',
    quickPicks: [45, 55, 65],
  },
  dayRate: {
    key: 'dayRate',
    label: 'Dagprijs (excl. btw)',
    tooltip: 'Alleen gebruiken als je hoofdzakelijk met dagprijs werkt. We rekenen dagprijs / 8.',
    typicalRange: 'Meestal 360–520 €/dag (bij timmermannen/ZZP)',
    min: 240,
    max: 1200,
    step: 10,
    unit: '€/dag',
    quickPicks: [360, 440, 520],
  },
  jobsPerMonth: {
    key: 'jobsPerMonth',
    label: 'Klussen per maand',
    tooltip: 'Afgeronde klussen in een gemiddelde maand.',
    typicalRange: 'Meestal 8–24 klussen/maand (bij timmermannen/ZZP)',
    min: 4,
    max: 40,
    step: 1,
    unit: 'klussen/maand',
    quickPicks: [8, 16, 24],
  },
  travelHoursPerWorkday: {
    key: 'travelHoursPerWorkday',
    label: 'Reistijd per werkdag (heen + terug)',
    tooltip: 'Totale reistijd per dag, heen en terug samen.',
    typicalRange: 'Meestal 0,5–1,5 uur/dag (bij timmermannen/ZZP)',
    min: 0,
    max: 3,
    step: 0.1,
    unit: 'uur/dag',
    quickPicks: [0.5, 1.0, 1.5],
  },
  parkingPerJob: {
    key: 'parkingPerJob',
    label: 'Parkeren/tol per klus',
    tooltip: 'Directe ritkosten zonder brandstof of reistijd.',
    typicalRange: 'Meestal 0–25 €/klus (bij timmermannen/ZZP)',
    min: 0,
    max: 80,
    step: 1,
    unit: '€/klus',
    quickPicks: [0, 10, 25],
  },
  adminHoursPerWeek: {
    key: 'adminHoursPerWeek',
    label: 'Offerte + administratie',
    tooltip: 'Offertes, facturen, bellen, corrigeren, herinneringen.',
    typicalRange: 'Meestal 3–8 uur/week (bij timmermannen/ZZP)',
    min: 0,
    max: 15,
    step: 0.5,
    unit: 'uur/week',
    quickPicks: [3, 5, 8],
  },
  urgentTripsPerMonth: {
    key: 'urgentTripsPerMonth',
    label: 'Spoedritten',
    tooltip: 'Extra ritten door missende spullen of verkeerde voorbereiding.',
    typicalRange: 'Meestal 0–3 ritten/maand (bij timmermannen/ZZP)',
    min: 0,
    max: 12,
    step: 1,
    unit: 'ritten/maand',
    quickPicks: [0, 1, 3],
  },
  callbackHoursPerMonth: {
    key: 'callbackHoursPerMonth',
    label: 'Nazorg/callback',
    tooltip: 'Service-uren die vaak niet volledig worden gefactureerd.',
    typicalRange: 'Meestal 0–4 uur/maand (bij timmermannen/ZZP)',
    min: 0,
    max: 12,
    step: 0.5,
    unit: 'uur/maand',
    quickPicks: [0, 2, 4],
  },
  forgotMaterialPerMonth: {
    key: 'forgotMaterialPerMonth',
    label: 'Vergeten materiaal',
    tooltip: 'Materiaal dat je wel koopt maar niet doorbelast.',
    typicalRange: 'Meestal 50–300 €/maand (bij timmermannen/ZZP)',
    min: 0,
    max: 1200,
    step: 5,
    unit: '€/maand',
    quickPicks: [50, 150, 300],
  },
  underpricedPercent: {
    key: 'underpricedPercent',
    label: 'Onderprijsde tijd',
    tooltip: 'Uren die te laag of niet worden doorberekend.',
    typicalRange: 'Meestal 2–10% (bij timmermannen/ZZP)',
    min: 0,
    max: 20,
    step: 1,
    unit: '%',
    quickPicks: [2, 5, 10],
  },
};

export const emptyUnknownSelection: UnknownSelection = {};

export function createAllUnknownSelection(): UnknownSelection {
  return {
    hourlyRate: true,
    dayRate: true,
    jobsPerMonth: true,
    travelHoursPerWorkday: true,
    parkingPerJob: true,
    adminHoursPerWeek: true,
    urgentTripsPerMonth: true,
    callbackHoursPerMonth: true,
    forgotMaterialPerMonth: true,
    underpricedPercent: true,
  };
}
