create extension if not exists pgcrypto;

create type public.ops_item_type as enum (
  'feedback',
  'website_request',
  'price_import_request',
  'custom_klus_request',
  'demo_request',
  'app_error',
  'n8n_incident',
  'data_quality_issue',
  'reddit_complaint'
);

create type public.ops_status as enum (
  'nieuw',
  'in_triage',
  'bezig',
  'geblokkeerd',
  'opgelost',
  'genegeerd'
);

create type public.ops_priority as enum (
  'laag',
  'medium',
  'hoog',
  'kritiek'
);

create type public.ops_severity as enum (
  'info',
  'waarschuwing',
  'error',
  'kritiek'
);

create table if not exists public.ops_owners (
  id uuid primary key default gen_random_uuid(),
  firebase_uid text unique,
  email text not null unique,
  display_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ops_items (
  id uuid primary key default gen_random_uuid(),
  type public.ops_item_type not null,
  title text not null,
  summary text,
  status public.ops_status not null default 'nieuw',
  priority public.ops_priority not null default 'medium',
  severity public.ops_severity not null default 'info',
  source_system text not null,
  source_collection text not null,
  source_record_id text not null,
  source_url text,
  owner_id uuid references public.ops_owners(id) on delete set null,
  sla_started_at timestamptz,
  sla_paused_at timestamptz,
  sla_stopped_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  snoozed_until timestamptz,
  resolution text,
  normalized_payload jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  tags_cache text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ops_items_source_dedupe_idx
  on public.ops_items (source_system, source_collection, source_record_id);

create index if not exists ops_items_type_idx on public.ops_items(type);
create index if not exists ops_items_status_idx on public.ops_items(status);
create index if not exists ops_items_priority_idx on public.ops_items(priority);
create index if not exists ops_items_updated_at_idx on public.ops_items(updated_at desc);

create table if not exists public.ops_item_notes (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.ops_items(id) on delete cascade,
  author_uid text not null,
  author_email text,
  note text not null,
  created_at timestamptz not null default now()
);

create index if not exists ops_item_notes_item_idx on public.ops_item_notes(item_id, created_at);

create table if not exists public.ops_item_events (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.ops_items(id) on delete cascade,
  actor_uid text,
  actor_email text,
  event_type text not null,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ops_item_events_item_idx on public.ops_item_events(item_id, created_at);

create table if not exists public.ops_tags (
  id uuid primary key default gen_random_uuid(),
  tag text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.ops_item_tags (
  item_id uuid not null references public.ops_items(id) on delete cascade,
  tag_id uuid not null references public.ops_tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (item_id, tag_id)
);

create index if not exists ops_item_tags_tag_idx on public.ops_item_tags(tag_id);

create table if not exists public.ops_source_sync_state (
  source_key text primary key,
  firestore_collection text,
  last_seen_created_at timestamptz,
  last_doc_id text,
  last_run_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.ops_ingest_failures (
  id bigint generated by default as identity primary key,
  source text not null,
  reason text not null,
  payload jsonb,
  recovered boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists ops_ingest_failures_source_idx on public.ops_ingest_failures(source, created_at desc);

create table if not exists public.ops_reddit_complaints (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null unique references public.ops_items(id) on delete cascade,
  subreddit text not null,
  post_id text not null,
  comment_id text not null,
  author text,
  score integer,
  customer_stage text,
  pain_topic text,
  sentiment text,
  urgency_score numeric,
  source_url text,
  post_title text,
  post_body text,
  comment_body text,
  run_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ops_reddit_dedupe_idx
  on public.ops_reddit_complaints(subreddit, post_id, comment_id);

create table if not exists public.ops_data_quality_issues (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null unique references public.ops_items(id) on delete cascade,
  check_key text not null,
  entity_type text not null,
  entity_ref text not null,
  failure_reason text not null,
  detected_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists ops_data_quality_dedupe_idx
  on public.ops_data_quality_issues(check_key, entity_type, entity_ref);

create or replace function public.ops_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_ops_owners_updated_at on public.ops_owners;
create trigger trg_ops_owners_updated_at
before update on public.ops_owners
for each row execute function public.ops_set_updated_at();

drop trigger if exists trg_ops_items_updated_at on public.ops_items;
create trigger trg_ops_items_updated_at
before update on public.ops_items
for each row execute function public.ops_set_updated_at();

drop trigger if exists trg_ops_reddit_updated_at on public.ops_reddit_complaints;
create trigger trg_ops_reddit_updated_at
before update on public.ops_reddit_complaints
for each row execute function public.ops_set_updated_at();

create or replace view public.ops_dashboard_daily as
select
  date_trunc('day', created_at) as day,
  count(*) as total_items,
  count(*) filter (where status = 'nieuw') as opened_items,
  count(*) filter (where status in ('opgelost', 'genegeerd')) as resolved_items,
  count(*) filter (where status not in ('opgelost', 'genegeerd')) as unresolved_items,
  count(*) filter (where priority = 'kritiek') as critical_items
from public.ops_items
group by 1;

create or replace view public.ops_sla_overview as
select
  id,
  type,
  status,
  priority,
  severity,
  source_system,
  source_collection,
  source_record_id,
  sla_started_at,
  sla_paused_at,
  sla_stopped_at,
  case
    when sla_started_at is null then null
    when sla_stopped_at is not null then extract(epoch from (sla_stopped_at - sla_started_at))::bigint
    when sla_paused_at is not null then extract(epoch from (sla_paused_at - sla_started_at))::bigint
    else extract(epoch from (now() - sla_started_at))::bigint
  end as sla_elapsed_seconds
from public.ops_items;

create or replace view public.ops_source_health as
with failures as (
  select
    source,
    count(*) filter (where created_at >= now() - interval '24 hours') as failures_24h
  from public.ops_ingest_failures
  group by source
)
select
  i.source_system,
  count(*) as total_items,
  count(*) filter (where i.status not in ('opgelost', 'genegeerd')) as open_items,
  max(i.updated_at) as last_item_at,
  coalesce(f.failures_24h, 0) as failures_24h
from public.ops_items i
left join failures f on f.source = i.source_system
group by i.source_system, f.failures_24h;
